
import javax.swing.JLabel;
import javax.swing.JRadioButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author skyli
 */
public class AdvancedFilter extends javax.swing.JFrame {

    /**
     * Creates new form AdvancedFilter
     */
    public AdvancedFilter() {
        initComponents();
        setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jHTTP = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jSSL = new javax.swing.JRadioButton();
        jFTP = new javax.swing.JRadioButton();
        jSSH = new javax.swing.JRadioButton();
        jTELNET = new javax.swing.JRadioButton();
        jDNS = new javax.swing.JRadioButton();
        jSMTP = new javax.swing.JRadioButton();
        jPOP = new javax.swing.JRadioButton();
        jIMAP = new javax.swing.JRadioButton();
        jIMAPS = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jHTTP.setText("HTTP (80)");
        jHTTP.setName("jHTTP"); // NOI18N
        jHTTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHTTPActionPerformed(evt);
            }
        });

        jLabel1.setText("Advanced filter");

        jSSL.setText("HTTP SSL (443)");
        jSSL.setName("jSSL"); // NOI18N
        jSSL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSSLActionPerformed(evt);
            }
        });

        jFTP.setText("FTP (21)");
        jFTP.setName("jFTP"); // NOI18N

        jSSH.setText("SSH (22)");
        jSSH.setName("jSSH"); // NOI18N
        jSSH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSSHActionPerformed(evt);
            }
        });

        jTELNET.setText("Telnet (23)");
        jTELNET.setName("jTELNET"); // NOI18N

        jDNS.setText("DNS (53)");
        jDNS.setName("jDNS"); // NOI18N

        jSMTP.setText("SMTP (25)");
        jSMTP.setName("jSMTP"); // NOI18N
        jSMTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSMTPActionPerformed(evt);
            }
        });

        jPOP.setText("POP3 (110)");
        jPOP.setName("jPOP"); // NOI18N
        jPOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPOPActionPerformed(evt);
            }
        });

        jIMAP.setText("IMAP (143)");
        jIMAP.setName("jIMAP"); // NOI18N

        jIMAPS.setText("IMAPS (993)");
        jIMAPS.setName("jIMAPS"); // NOI18N
        jIMAPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIMAPSActionPerformed(evt);
            }
        });

        jButton1.setText("Filter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTELNET)
                                    .addComponent(jFTP)
                                    .addComponent(jSSL)
                                    .addComponent(jHTTP)
                                    .addComponent(jSSH))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDNS)
                                    .addComponent(jIMAP)
                                    .addComponent(jPOP)
                                    .addComponent(jSMTP)
                                    .addComponent(jIMAPS))
                                .addGap(0, 35, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jHTTP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSSL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFTP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSSH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTELNET))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSMTP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPOP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jIMAP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jIMAPS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDNS)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jHTTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHTTPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jHTTPActionPerformed

    private void jSSLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSSLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSSLActionPerformed

    private void jSSHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSSHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSSHActionPerformed

    private void jSMTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSMTPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSMTPActionPerformed

    private void jPOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPOPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPOPActionPerformed

    private void jIMAPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIMAPSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIMAPSActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdvancedFilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdvancedFilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdvancedFilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdvancedFilter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdvancedFilter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JRadioButton jDNS;
    private javax.swing.JRadioButton jFTP;
    private javax.swing.JRadioButton jHTTP;
    private javax.swing.JRadioButton jIMAP;
    private javax.swing.JRadioButton jIMAPS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jPOP;
    private javax.swing.JRadioButton jSMTP;
    private javax.swing.JRadioButton jSSH;
    private javax.swing.JRadioButton jSSL;
    private javax.swing.JRadioButton jTELNET;
    // End of variables declaration//GEN-END:variables

    public JRadioButton getjDNS() {
        return jDNS;
    }

    public void setjDNS(JRadioButton jDNS) {
        this.jDNS = jDNS;
    }

    public JRadioButton getjFTP() {
        return jFTP;
    }

    public void setjFTP(JRadioButton jFTP) {
        this.jFTP = jFTP;
    }

    public JRadioButton getjHTTP() {
        return jHTTP;
    }

    public void setjHTTP(JRadioButton jHTTP) {
        this.jHTTP = jHTTP;
    }

    public JRadioButton getjIMAP() {
        return jIMAP;
    }

    public void setjIMAP(JRadioButton jIMAP) {
        this.jIMAP = jIMAP;
    }

    public JRadioButton getjIMAPS() {
        return jIMAPS;
    }

    public void setjIMAPS(JRadioButton jIMAPS) {
        this.jIMAPS = jIMAPS;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JRadioButton getjPOP() {
        return jPOP;
    }

    public void setjPOP(JRadioButton jPOP) {
        this.jPOP = jPOP;
    }

    public JRadioButton getjSMTP() {
        return jSMTP;
    }

    public void setjSMTP(JRadioButton jSMTP) {
        this.jSMTP = jSMTP;
    }

    public JRadioButton getjSSH() {
        return jSSH;
    }

    public void setjSSH(JRadioButton jSSH) {
        this.jSSH = jSSH;
    }

    public JRadioButton getjSSL() {
        return jSSL;
    }

    public void setjSSL(JRadioButton jSSL) {
        this.jSSL = jSSL;
    }

    public JRadioButton getjTELNET() {
        return jTELNET;
    }

    public void setjTELNET(JRadioButton jTELNET) {
        this.jTELNET = jTELNET;
    }
}
